[package]
name = "scoreboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-multiwin = "0.1.7"
serde = { version = "1.0.171", features = ["derive"] }
toml = "0.7.6"
